MATCHING_OUTPUT_SHEET_TITLE = 'TA-Matching Output'
ALTERNATES_OUTPUT_SHEET_TITLE = 'TA-Matching Output: Alternates'
REMOVE_TA_OUTPUT_SHEET_TITLE = 'TA-Matching Output: Remove TA'
ADDITIONAL_TA_OUTPUT_SHEET_TITLE = 'TA-Matching Output: Additional TA'
PLANNING_INPUT_STUDENTS_TAB_TITLE = 'Students'
PLANNING_INPUT_COURSES_TAB_TITLE = "Courses"
PREFERENCES_INPUT_TAB_TITLE = "Form Responses 1"
OUTPUT_TOC_TAB_TITLE = 'ToC'
